version: '3.7'

services:

  php:
    build:
      context: ./
      dockerfile: ./docker/build/php/Dockerfile
    volumes:
      - ./:/var/www/html

  nginx:
    build:
      context: ./
      dockerfile: ./docker/build/nginx/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    ports:
      - 80:80
